### ISSUE TITLE
Can't join because of online mode

### ISSUE THREAD

**Issue by bariscodefxy** [Aloento/CraftServer#33]
![resim](https://github.com/Aloento/CraftServer/assets/85716242/1233bc71-4afb-4064-9aec-4cbeb8e236f3)

I can't connect because I don't have premium account.

**Comment by Aloento** [comment]
Sad... @rainbowflesh 
I personally don't want to disable online mode.

**Comment by bariscodefxy** [comment]
> Sad... @rainbowflesh I personally don't want to disable online mode.

sad
